CREATE DATABASE IF NOT EXISTS school_db;

USE school_db;

CREATE TABLE IF NOT EXISTS students (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	class VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
	INDEX(email)
) AUTO_INCREMENT=100;
